steps:

- name: 'gcr.io/concrete-crow-244606/sonar-scanner:latest'
  args:
    - '-Dsonar.host.url=http://35.232.7.242:9000'
    - '-Dsonar.login=d57ef72497c93fb767e425f5a3d8ecfa6e801287'
    - '-Dsonar.projectKey=gitpos_code'
    - '-Dsonar.sources=./'
  
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install', '-Dmaven.test.skip=true']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/concrete-crow-244606/gke-poc:latest', '.']

#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['app', 'deploy', 'app.yaml', '--image-url', 'gcr.io/concrete-crow-244606/gke-poc']
    
images: ['gcr.io/concrete-crow-244606/gke-poc:latest']
